(ns leiningen.core.truss.project
  (:require [taoensso.truss            :as truss]
            [leiningen.core.truss.util :as util]))


(defn url?
  [string]
  (and
   (truss/have? string? string)
   (re-matches #"^(https?|ftp)://[^\s/$.?#]+\.?[^\s]*$" string)))

(defn validate-map
  "Validate that m is a valid Leiningen project map."
  [m]
  (truss/have map? m)
  (truss/have util/non-blank-string? (:description m))
  (truss/have url?                   (:url m))
  ;; (truss/have  (:mailing-list m))
  ;; (truss/have  (:mailing-lists m))
  ;; (truss/have  (:license m))
  ;; (truss/have  (:licenses m))
  ;; (truss/have  (:min-lein-version m))
  ;; (truss/have  (:dependencies m))
  ;; (truss/have  (:managed-dependencies m))
  ;; (truss/have  (:pedantic? m))
  ;; (truss/have  (:exclusions m))
  ;; (truss/have  (:plugins m))
  ;; (truss/have  (:repositories m))
  ;; (truss/have  (:plugin-repositories m))
  ;; (truss/have  (:mirrors m))
  ;; (truss/have  (:local-repo m))
  ;; (truss/have  (:update m))
  ;; (truss/have  (:checksum m))
  ;; (truss/have  (:offline? m))
  ;; (truss/have  (:deploy-repositories m))
  ;; (truss/have  (:signing m))
  ;; (truss/have  (:certificates m))
  ;; (truss/have  (:profiles m))
  ;; (truss/have  (:hooks m))
  ;; (truss/have  (:middleware m))
  ;; (truss/have  (:implicit-middleware m))
  ;; (truss/have  (:implicit-hooks m))
  ;; (truss/have  (:main m))
  ;; (truss/have  (:aliases m))
  ;; (truss/have  (:release-tasks m))
  ;; (truss/have  (:prep-tasks m))
  ;; (truss/have  (:aot m))
  ;; (truss/have  (:injections m))
  ;; (truss/have  (:java-agents m))
  ;; (truss/have  (:javac-options m))
  ;; (truss/have  (:warn-on-reflection m))
  ;; (truss/have  (:global-vars m))
  ;; (truss/have  (:java-cmd m))
  ;; (truss/have  (:jvm-opts m))
  ;; (truss/have  (:eval-in m))
  ;; (truss/have  (:bootclasspath m))
  ;; (truss/have  (:source-paths m))
  ;; (truss/have  (:java-source-paths m))
  ;; (truss/have  (:test-paths m))
  ;; (truss/have  (:resource-paths m))
  ;; (truss/have  (:target-path m))
  ;; (truss/have  (:compile-path m))
  ;; (truss/have  (:native-path m))
  ;; (truss/have  (:clean-targets m))
  ;; (truss/have  (:clean-non-project-classes m))
  ;; (truss/have  (:checkout-deps-shares m))
  ;; (truss/have  (:test-selectors m))
  ;; (truss/have  (:monkeypatch-clojure-test m))
  ;; (truss/have  (:repl-options m))
  ;; (truss/have  (:jar-name m))
  ;; (truss/have  (:uberjar-name m))
  ;; (truss/have  (:omit-source m))
  ;; (truss/have  (:jar-exclusions m))
  ;; (truss/have  (:jar-inclusions m))
  ;; (truss/have  (:uberjar-exclusions m))
  ;; (truss/have  (:auto-clean m))
  ;; (truss/have  (:uberjar-merge-with m))
  ;; (truss/have  (:filespecs m))
  ;; (truss/have  (:manifest m))
  ;; (truss/have  (:pom-location m))
  ;; (truss/have  (:parent m))
  ;; (truss/have  (:extensions m))
  ;; (truss/have  (:pom-plugins m))
  ;; (truss/have  (:pom-addition m))
  ;; (truss/have  (:scm m))
  ;; (truss/have  (:install-releases? m))
  ;; (truss/have  (:deploy-branches m))
  ;; (truss/have  (:classifiers m))
  )


(truss/have)
