(ns leiningen.core.truss.project
  (:require [taoensso.truss            :as truss]
            [leiningen.core.truss.util :as util]))


(defn url?   [string] (util/stregex-matches? #"^(https?|ftp)://[^\s/$.?#]+\.?[^\s]*$" string))
(defn email? [string] (util/stregex-matches? #"\S+@\S+\.?\S+"                         string))


;;; Mailing lists

(defn name?      [string] (util/non-blank-string? string))
(defn other-archives? [v] (util/multi-pred [vector? not-empty url?] v))
(defn subscribe? [string] (or (email? string) (url? string)))

(defn mailing-list? [m]
  (->> m
       (util/opt-key :name           name?)
       (util/opt-key :archive        url?)
       (util/opt-key :other-archives other-archives?)
       (util/opt-key :post           email?)
       (util/opt-key :subscribe      subscribe?)
       (util/opt-key :unsubscribe    subscribe?)))

(defn mailing-lists? [v]
  (util/multi-pred [not-empty vector?] v)
  (truss/have mailing-list? :in v))

(defn validate-map
  "Validate that m is a valid Leiningen project map."
  [m]
  (truss/have map? m)

  (util/opt-key :description   util/non-blank-string? m)
  (util/opt-key :url           url? m)
  (util/opt-key :mailing-list  mailing-list? m)
  (util/opt-key :mailing-lists mailing-lists? m)
  ;; (util/opt-key :license m)
  ;; (util/opt-key :licenses m)
  ;; (util/opt-key :min-lein-version m)
  ;; (util/opt-key :dependencies m)
  ;; (util/opt-key :managed-dependencies m)
  ;; (util/opt-key :pedantic? m)
  ;; (util/opt-key :exclusions m)
  ;; (util/opt-key :plugins m)
  ;; (util/opt-key :repositories m)
  ;; (util/opt-key :plugin-repositories m)
  ;; (util/opt-key :mirrors m)
  ;; (util/opt-key :local-repo m)
  ;; (util/opt-key :update m)
  ;; (util/opt-key :checksum m)
  ;; (util/opt-key :offline? m)
  ;; (util/opt-key :deploy-repositories m)
  ;; (util/opt-key :signing m)
  ;; (util/opt-key :certificates m)
  ;; (util/opt-key :profiles m)
  ;; (util/opt-key :hooks m)
  ;; (util/opt-key :middleware m)
  ;; (util/opt-key :implicit-middleware m)
  ;; (util/opt-key :implicit-hooks m)
  ;; (util/opt-key :main m)
  ;; (util/opt-key :aliases m)
  ;; (util/opt-key :release-tasks m)
  ;; (util/opt-key :prep-tasks m)
  ;; (util/opt-key :aot m)
  ;; (util/opt-key :injections m)
  ;; (util/opt-key :java-agents m)
  ;; (util/opt-key :javac-options m)
  ;; (util/opt-key :warn-on-reflection m)
  ;; (util/opt-key :global-vars m)
  ;; (util/opt-key :java-cmd m)
  ;; (util/opt-key :jvm-opts m)
  ;; (util/opt-key :eval-in m)
  ;; (util/opt-key :bootclasspath m)
  ;; (util/opt-key :source-paths m)
  ;; (util/opt-key :java-source-paths m)
  ;; (util/opt-key :test-paths m)
  ;; (util/opt-key :resource-paths m)
  ;; (util/opt-key :target-path m)
  ;; (util/opt-key :compile-path m)
  ;; (util/opt-key :native-path m)
  ;; (util/opt-key :clean-targets m)
  ;; (util/opt-key :clean-non-project-classes m)
  ;; (util/opt-key :checkout-deps-shares m)
  ;; (util/opt-key :test-selectors m)
  ;; (util/opt-key :monkeypatch-clojure-test m)
  ;; (util/opt-key :repl-options m)
  ;; (util/opt-key :jar-name m)
  ;; (util/opt-key :uberjar-name m)
  ;; (util/opt-key :omit-source m)
  ;; (util/opt-key :jar-exclusions m)
  ;; (util/opt-key :jar-inclusions m)
  ;; (util/opt-key :uberjar-exclusions m)
  ;; (util/opt-key :auto-clean m)
  ;; (util/opt-key :uberjar-merge-with m)
  ;; (util/opt-key :filespecs m)
  ;; (util/opt-key :manifest m)
  ;; (util/opt-key :pom-location m)
  ;; (util/opt-key :parent m)
  ;; (util/opt-key :extensions m)
  ;; (util/opt-key :pom-plugins m)
  ;; (util/opt-key :pom-addition m)
  ;; (util/opt-key :scm m)
  ;; (util/opt-key :install-releases? m)
  ;; (util/opt-key :deploy-branches m)
  ;; (util/opt-key :classifiers m)
  )
